export const calendarEvents = [
  {
    id: "1",
    title: "AP Bio Quiz - Cellular Respiration",
    classId: "ap-bio",
    className: "AP Biology",
    color: "#37E08D",
    date: "2025-10-01",
    type: "quiz",
  },
  {
    id: "2",
    title: "AP Calc Quiz - Derivatives",
    classId: "ap-calc",
    className: "AP Calculus AB",
    color: "#FFC857",
    date: "2025-10-01",
    type: "quiz",
  },
  {
    id: "3",
    title: "English Reading - Ch. 12",
    classId: "english-lit",
    className: "English Lit",
    color: "#FF4D57",
    date: "2025-10-03",
    type: "assignment",
  },
  {
    id: "4",
    title: "History Essay Draft",
    classId: "us-history",
    className: "US History",
    color: "#EB1F3A",
    date: "2025-10-04",
    type: "assignment",
  },
  {
    id: "5",
    title: "Bio Lab Report",
    classId: "ap-bio",
    className: "AP Biology",
    color: "#37E08D",
    date: "2025-10-07",
    type: "assignment",
  },
  {
    id: "6",
    title: "Calc Test - Integration",
    classId: "ap-calc",
    className: "AP Calculus AB",
    color: "#FFC857",
    date: "2025-10-10",
    type: "test",
  },
]
