export const practiceQueue = [
  {
    id: "1",
    title: "Cellular Respiration - Mixed Review",
    classId: "ap-bio",
    className: "AP Biology",
    color: "#37E08D",
    questions: 20,
    timeEstimate: "15 min",
    difficulty: "Adaptive",
    concepts: ["Glycolysis", "Krebs Cycle", "ETC"],
    progress: 0,
    streak: 0,
  },
  {
    id: "2",
    title: "Derivatives - Quick Practice",
    classId: "ap-calc",
    className: "AP Calculus AB",
    color: "#FFC857",
    questions: 15,
    timeEstimate: "10 min",
    difficulty: "Medium",
    concepts: ["Power Rule", "Chain Rule", "Product Rule"],
    progress: 40,
    streak: 3,
  },
  {
    id: "3",
    title: "Symbolism Analysis",
    classId: "english-lit",
    className: "English Lit",
    color: "#FF4D57",
    questions: 10,
    timeEstimate: "8 min",
    difficulty: "Hard",
    concepts: ["Literary Devices", "Theme Analysis"],
    progress: 100,
    streak: 7,
  },
  {
    id: "4",
    title: "Civil War Era - Key Events",
    classId: "us-history",
    className: "US History",
    color: "#EB1F3A",
    questions: 25,
    timeEstimate: "18 min",
    difficulty: "Easy",
    concepts: ["Timeline", "Key Figures", "Battles"],
    progress: 60,
    streak: 5,
  },
]
